import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import React, {useEffect, useRef, useLayoutEffect } from 'react';

import { gsap } from "gsap/dist/gsap";
import { ScrollTrigger } from "gsap/dist/ScrollTrigger";
import Layout from '../components/layout'

export default function Home() {

	 const videoRef = useRef();

    useEffect(() => {

        setTimeout(()=>{
            videoRef.current.play()
        },2000)
    }, []);
	useLayoutEffect(() => {
		  gsap.registerPlugin(ScrollTrigger);
		  ScrollTrigger.normalizeScroll(true)
		
ScrollTrigger.create({
  trigger: ".box",
  pin: true,
  start: "center center",
  end: "+=250",
  markers: false
});
		
	},[]);
	
  return (
  
    <>
	
      <Head>
        <title>Home | YB</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
	
      </Head>
     
        <section className="slider">
 <video id="slider-video" poster="/slider.jpg"
            ref={videoRef}
            loop
            muted
            >
               <source src="/video.mp4" type="video/mp4"/>
			   <source src="/video.ogg" type="video/ogg"/>
       </video>
		
		   <div className="slider-content">
		   <div className="brand-name">Car Beukers</div>
		   <div className="container position-relative">
		       <div className="row">
			      <div className="col-md-6">
				     <div className="title">Beukers <br/>
Automotive</div>
                  <div className="btn-box">
				  <a hraf="#" className="btn btn-secondary">Contact</a>
				  <a hraf="#" className="btn btn-primary">Collectie</a>
				  </div>
				  </div>
				  <div className="col-md-6">
				    
				  </div>
			   </div>
			   </div>
		   </div>
		</section> 
		<div className="about">
			<div className="container">
				<div className="row">
					<div className="col-md-6">
						<div className="title">Beuk de weg op met <br/> Beuker&apos;s bolides!</div>
					</div>
					<div className="col-md-6">
						<p>Van klassiekers tot moderne parels, onze collectie aan unieke en bijzondere auto&apos;s staat klaar om ontdekt te worden. Neem een kijkje en vind de wagen die jouw hart sneller laat kloppen.</p>
					</div>
				</div>
			</div>
		</div>
		<section className="insurance">
			<div className="container-fluid">
			    <div className="row d-flex align-items-center">
					<div className="col-md-6">
					<div className="box" data-speed="1.5">
						<div className="title">About<span>.</span></div>
						<div className="subtitle">Vol gas naar je droom auto</div>
						<p>Auto&apos;s zijn mijn ding. Wat startte als een hobby, explodeert nu! Mijn garage staat voller dan ooit en ik voel dat het tijd is om te schakelen. Niet omdat ik deze prachtige machines niet waardeer, maar om ruimte te creëren voor nieuwe krachtpatsers. Ik zet nu de stap om mijn eigen autobedrijf te lanceren, zodat ik vol gas mijn passie kan volgen en tegelijkertijd andere autoliefhebbers een unieke ervaring kan bieden!</p>
					</div>
					</div>
					<div className="col-md-6">
						<Image src="/insurance-02.png" width={0} height={0} sizes="100vw" style={{ width: '100%', height: 'auto' }} alt="insurance"/>
					</div>
				</div>
			</div>
		</section>
      
    </>
  )
}
Home.getLayout = function getLayout(page) {
	return (
		<Layout>
			{page}
		</Layout>
	)
}